baseURL: /

publishDir: "public"
languageCode: en-us
title: "Scaling Contact Tracing"
theme: "scalingct-theme"

canonifyURLs: true
enableRobotsTXT: true
sectionPagesMenu: main

params:
  description: "There is a lot of information on the internet about contact tracing. We used our network to find the best contact tracing playbooks so that we could recommend one destination to our partners. As we worked with more partners, it became clear that this info was helpful beyond our world. Here is the curated list of Contact Tracing Playbooks that we have found."
  author: "U.S. Digital Response"
  keywords: "contact tracing, contact tracing playbook, us digital response, contact tracing"
  name: "Scaling Contact Tracing"
  email: contact@usdigitalresponse.org
  github: harperreed/ct-playbooks

  
disableKinds:
  - taxonomy
  - taxonomyTerm
  - rss
  - section

markup:
  goldmark:
    renderer:
      unsafe: true
